Develop to main. Service with comments
BykovIvan/java-explore-with-me pull request #4
Opened 2022-10-17 22:35 UTC by BykovIvan

2022-10-17 23:29 UTC, db-exp commented on docker-compose.yml
> +      - explore_with_me_statistics=http://stats-server:9090
Лучше тоже в UPPER CASE

2022-10-18 11:45 UTC, db-exp requested changes

2022-10-18 11:45 UTC, db-exp commented on server/src/main/java/ru/bykov/explore/clientstat/StatClient.java
> +    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
private static лучше добавить

2022-10-18 11:45 UTC, db-exp commented on server/src/main/java/ru/bykov/explore/controllers/admin/CommentControllerAdmin.java
> +                                    @RequestBody UpdateCommentByAdmin updateCommentByAdmin) {
Valid хорошо бы добавить и аннотации валидации на dto - size, null итп

2022-10-18 11:45 UTC, db-exp commented on server/src/main/java/ru/bykov/explore/controllers/admin/EventControllerAdmin.java
> +    public EventFullDto updateById(@PathVariable("eventId") Long eventId,
Valid хорошо бы добавить и аннотации валидации на dto - size, null итп

2022-10-18 11:45 UTC, db-exp commented on server/src/main/java/ru/bykov/explore/exceptions/model/ApiSubError.java
> +public abstract class ApiSubError {
можно интерфейсом сделать

2022-10-18 11:45 UTC, db-exp commented on server/src/main/java/ru/bykov/explore/model/Category.java
> +    @Column(unique = true)
Нужно size добавить/null (да/нет) итд как аннотации валидации, у самой колонки по умолчанию nullable=true

2022-10-18 11:45 UTC, db-exp commented on server/src/main/java/ru/bykov/explore/model/Comment.java
> +    private String text;
Нужно size добавить/null (да/нет) итд как аннотации валидации, у самой колонки по умолчанию nullable=true

2022-10-18 11:45 UTC, db-exp commented on server/src/main/java/ru/bykov/explore/model/Compilation.java
> +    private String title;                   //Заголовок подборки
Нужно size добавить/null (да/нет) итд как аннотации валидации, у самой колонки по умолчанию nullable=true

2022-10-18 11:45 UTC, db-exp commented on server/src/main/java/ru/bykov/explore/model/Event.java
> +    private String title;
Нужно size добавить/null (да/нет) итд как аннотации валидации, у самой колонки по умолчанию nullable=true

2022-10-18 11:45 UTC, db-exp commented on statistics/src/main/java/ru/bykov/explore/service/impl/StatisticServiceImpl.java
> +        if (Boolean.TRUE.equals(unique))
почему не просто if(unique)?

2022-10-18 11:45 UTC, db-exp commented on statistics/src/main/java/ru/bykov/explore/model/dto/EndPointHit.java
> +public class EndPointHit {
Нужно size добавить/null (да/нет) итд как аннотации валидации

2022-10-18 11:45 UTC, db-exp commented on statistics/src/main/java/ru/bykov/explore/model/Statistic.java
> +public class Statistic {
Нужно size добавить/null (да/нет) итд как аннотации валидации

2022-10-18 11:45 UTC, db-exp commented on statistics/src/main/java/ru/bykov/explore/controller/StatisticController.java
> +    public void createStat(@RequestBody EndPointHit endPointHit) {
Нужно добавить Valid

2022-10-18 11:45 UTC, db-exp commented on server/src/main/java/ru/bykov/explore/services/impl/EventServiceImpl.java
> +    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
private static?

2022-10-18 11:45 UTC, db-exp commented on server/src/main/java/ru/bykov/explore/repositories/RequestRepository.java
> +            "where r.status IN (:oldStatus) " +
IN - если много, тут =

2022-10-18 11:45 UTC, db-exp commented on server/src/main/java/ru/bykov/explore/model/dto/user/UserDto.java
> +@Getter
Можно Data вместо Getter/Setter/ToString

2022-10-18 11:45 UTC, db-exp commented on server/src/main/java/ru/bykov/explore/model/dto/event/UpdateEventRequest.java
> +public class UpdateEventRequest {
Не хватает аннотаций валидации size/null итд

2022-10-18 11:45 UTC, db-exp commented on server/src/main/java/ru/bykov/explore/model/dto/event/AdminUpdateEventRequest.java
> +public class AdminUpdateEventRequest {
Не хватает аннотаций валидации size/null итд

2022-10-18 11:45 UTC, db-exp commented on server/src/main/java/ru/bykov/explore/model/User.java
> +public class User {
Не хватает аннотаций валидации size/null итд

2022-10-18 11:45 UTC, db-exp commented on server/src/main/java/ru/bykov/explore/model/dto/comment/UpdateCommentByAdmin.java
> +public class UpdateCommentByAdmin {
Хорошо бы добавить аннотации валидации

2022-10-18 12:14 UTC, BykovIvan commented on server/src/main/java/ru/bykov/explore/model/dto/user/UserDto.java
> +@Getter
Была Data, прочитал про коллизии в Dto с использованием @Data , поменял на Сеттер, Геттер и туСтринг

2022-10-18 12:28 UTC, BykovIvan commented on server/src/main/java/ru/bykov/explore/controllers/admin/EventControllerAdmin.java
> +    public EventFullDto updateById(@PathVariable("eventId") Long eventId,
Из ТЗ
PUT
/admin/events/{eventId}
Редактирование события
Редактирование данных любого события администратором. Валидация данных не требуется.

2022-10-18 12:42 UTC, BykovIvan commented on server/src/main/java/ru/bykov/explore/controllers/admin/CommentControllerAdmin.java
> +                                    @RequestBody UpdateCommentByAdmin updateCommentByAdmin) {
Согласен, добавил. Просто руководствовался тем, что это администратор, и ему все можно, так же как в тз написано.

2022-10-18 12:42 UTC, BykovIvan commented on server/src/main/java/ru/bykov/explore/exceptions/model/ApiSubError.java
> +public abstract class ApiSubError {
Согласен

2022-10-18 12:48 UTC, BykovIvan commented on server/src/main/java/ru/bykov/explore/model/Category.java
> +    @Column(unique = true)
Вопрос, а замет тут валидация? Создавать и редактировать я могу только с помощью дтошек. Там будет проверка на валидацию, а тут для чего?

2022-10-18 22:45 UTC, BykovIvan commented on server/src/main/java/ru/bykov/explore/model/dto/comment/UpdateCommentByAdmin.java
> +public class UpdateCommentByAdmin {
+

2022-10-18 22:45 UTC, BykovIvan commented on server/src/main/java/ru/bykov/explore/model/User.java
> +public class User {
+

2022-10-18 22:45 UTC, BykovIvan commented on server/src/main/java/ru/bykov/explore/model/dto/event/AdminUpdateEventRequest.java
> +public class AdminUpdateEventRequest {
+

2022-10-19 19:35 UTC, db-exp approved these changes

2022-10-19 19:45 UTC, merged